name: task_assist
description: "A to do list application."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/images/

  uses-material-design: true

  fonts:
    - family: Belleza
      fonts:
        - asset: assets/fonts/Belleza-Regular.ttf
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
    - family: Sora
      fonts:
        - asset: assets/fonts/Sora-Regular.ttf
